-- Golang Questions
INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('Which Go package is the standard interface for interacting with databases?', '["database/sql", "mysql", "sqlx", "gorm"]', 'database/sql', 'go'),
('What function is used to open a database connection in Go?', '["sql.Open()", "database.Connect()", "sql.Connect()", "db.Open()"]', 'sql.Open()', 'go'),
('How do you ensure a database connection is closed after use?', '["defer db.Close()", "db.Close()", "db.Shutdown()", "defer database.Close()"]', 'defer db.Close()', 'go'),
('Which method executes a query that doesn''t return any rows, like an INSERT or UPDATE?', '["db.Exec()", "db.Query()", "db.Ping()", "db.Prepare()"]', 'db.Exec()', 'go'),
('How do you retrieve rows from a database in Go?', '["db.Query()", "db.Exec()", "db.Scan()", "db.Get()"]', 'db.Query()', 'go'),
('What is the main purpose of using prepared statements?', '["Preventing SQL injection", "Improving database performance", "Using dynamic SQL queries", "Handling multiple connections"]', 'Preventing SQL injection', 'go'),
('What Go standard library function is used to get the result of a prepared statement execution, such as the last inserted ID?', '["Result.LastInsertId()", "Rows.LastInsertId()", "Stmt.LastInsertId()", "db.LastInsertId()"]', 'Result.LastInsertId()', 'go'),
('When scanning a nullable `varchar` from a MySQL database into a Go `string` variable, what type should you use?', '["sql.NullString", "string", "NullString", "NullableString"]', 'sql.NullString', 'go'),
('Which of the following is the correct way to start a transaction in Go?', '["tx, _ := db.Begin()", "db.StartTransaction()", "tx, _ := sql.Begin()", "db.Transaction()"]', 'tx, _ := db.Begin()', 'go'),
('What is the purpose of `defer tx.Rollback()` in a transaction block?', '["To ensure the transaction is rolled back if an error occurs", "To commit the transaction if an error occurs", "To start a new transaction", "To close the transaction"]', 'To ensure the transaction is rolled back if an error occurs', 'go'),
('How do you iterate through the results of `db.Query()`?', '["using a for loop with `rows.Next()`", "using `rows.Scan()` in a loop", "using a `for each` loop", "the `Query()` function returns a list"]', 'using a for loop with `rows.Next()`', 'go'),
('What does `rows.Scan()` do?', '["Scans the current row''s columns into Go variables", "Executes the SQL query", "Retrieves all rows at once", "Closes the row set"]', 'Scans the current row''s columns into Go variables', 'go'),
('Which package is commonly used as a MySQL driver for the `database/sql` package?', '["github.com/go-sql-driver/mysql", "go-mysql", "golang-mysql", "mysql-connector"]', 'github.com/go-sql-driver/mysql', 'go'),
('What is a connection pool?', '["A cache for storing SQL queries", "A set of open connections to the database", "A list of database users", "A way to define database schema"]', 'A set of open connections to the database', 'go'),
('What is the correct way to set the maximum number of open connections in a pool?', '["db.SetMaxOpenConns(n)", "db.SetConnections(n)", "db.SetPoolSize(n)", "db.SetMaxConnections(n)"]', 'db.SetMaxOpenConns(n)', 'go'),
('When is `db.Ping()` useful?', '["To check if the database connection is alive", "To run a simple query", "To close a connection", "To start a transaction"]', 'To check if the database connection is alive', 'go'),
('Which of the following is an example of a good placeholder for a prepared statement?', '["?", ":name", "$1", "#"]', '?', 'go'),
('How do you execute an `INSERT` statement and get the number of affected rows?', '["`Result.RowsAffected()`", "`db.Exec().RowsAffected()`", "`rows.RowsAffected()`", "`stmt.RowsAffected()`"]', '`Result.RowsAffected()`', 'go'),
('What happens if you forget to call `rows.Close()`?', '["The database connection will not be released back to the pool", "The program will crash", "Nothing, it''s handled automatically", "The query will fail"]', 'The database connection will not be released back to the pool', 'go'),
('In a Go web application, where is the best place to initialize the database connection pool?', '["In the `main` function", "In every handler function", "As a global variable", "In a goroutine"]', 'In the `main` function', 'go');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'python'),
('question2','["a","b","c","d"]', 'a', 'python'),
('question3','["a","b","c","d"]', 'a', 'python'),
('question4','["a","b","c","d"]', 'a', 'python'),
('question5','["a","b","c","d"]', 'a', 'python'),
('question6','["a","b","c","d"]', 'a', 'python'),
('question7','["a","b","c","d"]', 'a', 'python'),
('question8','["a","b","c","d"]', 'a', 'python'),
('question9','["a","b","c","d"]', 'a', 'python'),
('question10','["a","b","c","d"]', 'a', 'python'),
('question11','["a","b","c","d"]', 'a', 'python'),
('question12','["a","b","c","d"]', 'a', 'python'),
('question13','["a","b","c","d"]', 'a', 'python'),
('question14','["a","b","c","d"]', 'a', 'python'),
('question15','["a","b","c","d"]', 'a', 'python'),
('question16','["a","b","c","d"]', 'a', 'python'),
('question17','["a","b","c","d"]', 'a', 'python'),
('question18','["a","b","c","d"]', 'a', 'python'),
('question19','["a","b","c","d"]', 'a', 'python'),
('question20','["a","b","c","d"]', 'a', 'python');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'java'),
('question2','["a","b","c","d"]', 'a', 'java'),
('question3','["a","b","c","d"]', 'a', 'java'),
('question4','["a","b","c","d"]', 'a', 'java'),
('question5','["a","b","c","d"]', 'a', 'java'),
('question6','["a","b","c","d"]', 'a', 'java'),
('question7','["a","b","c","d"]', 'a', 'java'),
('question8','["a","b","c","d"]', 'a', 'java'),
('question9','["a","b","c","d"]', 'a', 'java'),
('question10','["a","b","c","d"]', 'a', 'java'),
('question11','["a","b","c","d"]', 'a', 'java'),
('question12','["a","b","c","d"]', 'a', 'java'),
('question13','["a","b","c","d"]', 'a', 'java'),
('question14','["a","b","c","d"]', 'a', 'java'),
('question15','["a","b","c","d"]', 'a', 'java'),
('question16','["a","b","c","d"]', 'a', 'java'),
('question17','["a","b","c","d"]', 'a', 'java'),
('question18','["a","b","c","d"]', 'a', 'java'),
('question19','["a","b","c","d"]', 'a', 'java'),
('question20','["a","b","c","d"]', 'a', 'java');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'c'),
('question2','["a","b","c","d"]', 'a', 'c'),
('question3','["a","b","c","d"]', 'a', 'c'),
('question4','["a","b","c","d"]', 'a', 'c'),
('question5','["a","b","c","d"]', 'a', 'c'),
('question6','["a","b","c","d"]', 'a', 'c'),
('question7','["a","b","c","d"]', 'a', 'c'),
('question8','["a","b","c","d"]', 'a', 'c'),
('question9','["a","b","c","d"]', 'a', 'c'),
('question10','["a","b","c","d"]', 'a', 'c'),
('question11','["a","b","c","d"]', 'a', 'c'),
('question12','["a","b","c","d"]', 'a', 'c'),
('question13','["a","b","c","d"]', 'a', 'c'),
('question14','["a","b","c","d"]', 'a', 'c'),
('question15','["a","b","c","d"]', 'a', 'c'),
('question16','["a","b","c","d"]', 'a', 'c'),
('question17','["a","b","c","d"]', 'a', 'c'),
('question18','["a","b","c","d"]', 'a', 'c'),
('question19','["a","b","c","d"]', 'a', 'c'),
('question20','["a","b","c","d"]', 'a', 'c');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'c++'),
('question2','["a","b","c","d"]', 'a', 'c++'),
('question3','["a","b","c","d"]', 'a', 'c++'),
('question4','["a","b","c","d"]', 'a', 'c++'),
('question5','["a","b","c","d"]', 'a', 'c++'),
('question6','["a","b","c","d"]', 'a', 'c++'),
('question7','["a","b","c","d"]', 'a', 'c++'),
('question8','["a","b","c","d"]', 'a', 'c++'),
('question9','["a","b","c","d"]', 'a', 'c++'),
('question10','["a","b","c","d"]', 'a', 'c++'),
('question11','["a","b","c","d"]', 'a', 'c++'),
('question12','["a","b","c","d"]', 'a', 'c++'),
('question13','["a","b","c","d"]', 'a', 'c++'),
('question14','["a","b","c","d"]', 'a', 'c++'),
('question15','["a","b","c","d"]', 'a', 'c++'),
('question16','["a","b","c","d"]', 'a', 'c++'),
('question17','["a","b","c","d"]', 'a', 'c++'),
('question18','["a","b","c","d"]', 'a', 'c++'),
('question19','["a","b","c","d"]', 'a', 'c++'),
('question20','["a","b","c","d"]', 'a', 'c++');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'zig'),
('question2','["a","b","c","d"]', 'a', 'zig'),
('question3','["a","b","c","d"]', 'a', 'zig'),
('question4','["a","b","c","d"]', 'a', 'zig'),
('question5','["a","b","c","d"]', 'a', 'zig'),
('question6','["a","b","c","d"]', 'a', 'zig'),
('question7','["a","b","c","d"]', 'a', 'zig'),
('question8','["a","b","c","d"]', 'a', 'zig'),
('question9','["a","b","c","d"]', 'a', 'zig'),
('question10','["a","b","c","d"]', 'a', 'zig'),
('question11','["a","b","c","d"]', 'a', 'zig'),
('question12','["a","b","c","d"]', 'a', 'zig'),
('question13','["a","b","c","d"]', 'a', 'zig'),
('question14','["a","b","c","d"]', 'a', 'zig'),
('question15','["a","b","c","d"]', 'a', 'zig'),
('question16','["a","b","c","d"]', 'a', 'zig'),
('question17','["a","b","c","d"]', 'a', 'zig'),
('question18','["a","b","c","d"]', 'a', 'zig'),
('question19','["a","b","c","d"]', 'a', 'zig'),
('question20','["a","b","c","d"]', 'a', 'zig');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'rust'),
('question2','["a","b","c","d"]', 'a', 'rust'),
('question3','["a","b","c","d"]', 'a', 'rust'),
('question4','["a","b","c","d"]', 'a', 'rust'),
('question5','["a","b","c","d"]', 'a', 'rust'),
('question6','["a","b","c","d"]', 'a', 'rust'),
('question7','["a","b","c","d"]', 'a', 'rust'),
('question8','["a","b","c","d"]', 'a', 'rust'),
('question9','["a","b","c","d"]', 'a', 'rust'),
('question10','["a","b","c","d"]', 'a', 'rust'),
('question11','["a","b","c","d"]', 'a', 'rust'),
('question12','["a","b","c","d"]', 'a', 'rust'),
('question13','["a","b","c","d"]', 'a', 'rust'),
('question14','["a","b","c","d"]', 'a', 'rust'),
('question15','["a","b","c","d"]', 'a', 'rust'),
('question16','["a","b","c","d"]', 'a', 'rust'),
('question17','["a","b","c","d"]', 'a', 'rust'),
('question18','["a","b","c","d"]', 'a', 'rust'),
('question19','["a","b","c","d"]', 'a', 'rust'),
('question20','["a","b","c","d"]', 'a', 'rust');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'ocaml'),
('question2','["a","b","c","d"]', 'a', 'ocaml'),
('question3','["a","b","c","d"]', 'a', 'ocaml'),
('question4','["a","b","c","d"]', 'a', 'ocaml'),
('question5','["a","b","c","d"]', 'a', 'ocaml'),
('question6','["a","b","c","d"]', 'a', 'ocaml'),
('question7','["a","b","c","d"]', 'a', 'ocaml'),
('question8','["a","b","c","d"]', 'a', 'ocaml'),
('question9','["a","b","c","d"]', 'a', 'ocaml'),
('question10','["a","b","c","d"]', 'a', 'ocaml'),
('question11','["a","b","c","d"]', 'a', 'ocaml'),
('question12','["a","b","c","d"]', 'a', 'ocaml'),
('question13','["a","b","c","d"]', 'a', 'ocaml'),
('question14','["a","b","c","d"]', 'a', 'ocaml'),
('question15','["a","b","c","d"]', 'a', 'ocaml'),
('question16','["a","b","c","d"]', 'a', 'ocaml'),
('question17','["a","b","c","d"]', 'a', 'ocaml'),
('question18','["a","b","c","d"]', 'a', 'ocaml'),
('question19','["a","b","c","d"]', 'a', 'ocaml'),
('question20','["a","b","c","d"]', 'a', 'ocaml');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'javascript'),
('question2','["a","b","c","d"]', 'a', 'javascript'),
('question3','["a","b","c","d"]', 'a', 'javascript'),
('question4','["a","b","c","d"]', 'a', 'javascript'),
('question5','["a","b","c","d"]', 'a', 'javascript'),
('question6','["a","b","c","d"]', 'a', 'javascript'),
('question7','["a","b","c","d"]', 'a', 'javascript'),
('question8','["a","b","c","d"]', 'a', 'javascript'),
('question9','["a","b","c","d"]', 'a', 'javascript'),
('question10','["a","b","c","d"]', 'a', 'javascript'),
('question11','["a","b","c","d"]', 'a', 'javascript'),
('question12','["a","b","c","d"]', 'a', 'javascript'),
('question13','["a","b","c","d"]', 'a', 'javascript'),
('question14','["a","b","c","d"]', 'a', 'javascript'),
('question15','["a","b","c","d"]', 'a', 'javascript'),
('question16','["a","b","c","d"]', 'a', 'javascript'),
('question17','["a","b","c","d"]', 'a', 'javascript'),
('question18','["a","b","c","d"]', 'a', 'javascript'),
('question19','["a","b","c","d"]', 'a', 'javascript'),
('question20','["a","b","c","d"]', 'a', 'javascript');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'ruby'),
('question2','["a","b","c","d"]', 'a', 'ruby'),
('question3','["a","b","c","d"]', 'a', 'ruby'),
('question4','["a","b","c","d"]', 'a', 'ruby'),
('question5','["a","b","c","d"]', 'a', 'ruby'),
('question6','["a","b","c","d"]', 'a', 'ruby'),
('question7','["a","b","c","d"]', 'a', 'ruby'),
('question8','["a","b","c","d"]', 'a', 'ruby'),
('question9','["a","b","c","d"]', 'a', 'ruby'),
('question10','["a","b","c","d"]', 'a', 'ruby'),
('question11','["a","b","c","d"]', 'a', 'ruby'),
('question12','["a","b","c","d"]', 'a', 'ruby'),
('question13','["a","b","c","d"]', 'a', 'ruby'),
('question14','["a","b","c","d"]', 'a', 'ruby'),
('question15','["a","b","c","d"]', 'a', 'ruby'),
('question16','["a","b","c","d"]', 'a', 'ruby'),
('question17','["a","b","c","d"]', 'a', 'ruby'),
('question18','["a","b","c","d"]', 'a', 'ruby'),
('question19','["a","b","c","d"]', 'a', 'ruby'),
('question20','["a","b","c","d"]', 'a', 'ruby');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'kotlin'),
('question2','["a","b","c","d"]', 'a', 'kotlin'),
('question3','["a","b","c","d"]', 'a', 'kotlin'),
('question4','["a","b","c","d"]', 'a', 'kotlin'),
('question5','["a","b","c","d"]', 'a', 'kotlin'),
('question6','["a","b","c","d"]', 'a', 'kotlin'),
('question7','["a","b","c","d"]', 'a', 'kotlin'),
('question8','["a","b","c","d"]', 'a', 'kotlin'),
('question9','["a","b","c","d"]', 'a', 'kotlin'),
('question10','["a","b","c","d"]', 'a', 'kotlin'),
('question11','["a","b","c","d"]', 'a', 'kotlin'),
('question12','["a","b","c","d"]', 'a', 'kotlin'),
('question13','["a","b","c","d"]', 'a', 'kotlin'),
('question14','["a","b","c","d"]', 'a', 'kotlin'),
('question15','["a","b","c","d"]', 'a', 'kotlin'),
('question16','["a","b","c","d"]', 'a', 'kotlin'),
('question17','["a","b","c","d"]', 'a', 'kotlin'),
('question18','["a","b","c","d"]', 'a', 'kotlin'),
('question19','["a","b","c","d"]', 'a', 'kotlin'),
('question20','["a","b","c","d"]', 'a', 'kotlin');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'lua'),
('question2','["a","b","c","d"]', 'a', 'lua'),
('question3','["a","b","c","d"]', 'a', 'lua'),
('question4','["a","b","c","d"]', 'a', 'lua'),
('question5','["a","b","c","d"]', 'a', 'lua'),
('question6','["a","b","c","d"]', 'a', 'lua'),
('question7','["a","b","c","d"]', 'a', 'lua'),
('question8','["a","b","c","d"]', 'a', 'lua'),
('question9','["a","b","c","d"]', 'a', 'lua'),
('question10','["a","b","c","d"]', 'a', 'lua'),
('question11','["a","b","c","d"]', 'a', 'lua'),
('question12','["a","b","c","d"]', 'a', 'lua'),
('question13','["a","b","c","d"]', 'a', 'lua'),
('question14','["a","b","c","d"]', 'a', 'lua'),
('question15','["a","b","c","d"]', 'a', 'lua'),
('question16','["a","b","c","d"]', 'a', 'lua'),
('question17','["a","b","c","d"]', 'a', 'lua'),
('question18','["a","b","c","d"]', 'a', 'lua'),
('question19','["a","b","c","d"]', 'a', 'lua'),
('question20','["a","b","c","d"]', 'a', 'lua');

INSERT INTO questions (`question`, `options`, `answer`, `topic`) VALUES
('question1','["a","b","c","d"]', 'a', 'shell'),
('question2','["a","b","c","d"]', 'a', 'shell'),
('question3','["a","b","c","d"]', 'a', 'shell'),
('question4','["a","b","c","d"]', 'a', 'shell'),
('question5','["a","b","c","d"]', 'a', 'shell'),
('question6','["a","b","c","d"]', 'a', 'shell'),
('question7','["a","b","c","d"]', 'a', 'shell'),
('question8','["a","b","c","d"]', 'a', 'shell'),
('question9','["a","b","c","d"]', 'a', 'shell'),
('question10','["a","b","c","d"]', 'a', 'shell'),
('question11','["a","b","c","d"]', 'a', 'shell'),
('question12','["a","b","c","d"]', 'a', 'shell'),
('question13','["a","b","c","d"]', 'a', 'shell'),
('question14','["a","b","c","d"]', 'a', 'shell'),
('question15','["a","b","c","d"]', 'a', 'shell'),
('question16','["a","b","c","d"]', 'a', 'shell'),
('question17','["a","b","c","d"]', 'a', 'shell'),
('question18','["a","b","c","d"]', 'a', 'shell'),
('question19','["a","b","c","d"]', 'a', 'shell'),
('question20','["a","b","c","d"]', 'a', 'shell');
