openapi: 3.0.3
info:
  title: Quiz Microservices API
  description: Complete API documentation for all 5 microservices (Client, Session Manager, Quiz Manager, Report Generator, Email Service)
  version: 1.0.0
servers:
  - url: http://localhost:8080
  
tags:
  - name: Quiz Manager
    description: Manages the quizes

paths:
  /quiz/generate:
    post:
      tags:
        - Quiz Manager
      summary: Generate quiz for user
      requestBody:
        $ref: '#/components/requestBodies/GenerateQuiz'
      responses:
        '200':
          description: Quiz questions returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Questions'
        '400':
          description: Invalid request
        '401':
          description: Unauthenticated
        '403':
          description: forbidden
        '404':
          description: topic not found
        '500':
          description: internal server error
              
  /quiz/store-answer:
    post:
      tags:
        - Quiz Manager
      summary: Store submitted answers
      requestBody:
        $ref: '#/components/requestBodies/StoreAnswer'
      responses:
        '204':
          description: Answers stored in DB
        '400':
          description: Invalid request
        '401':
          description: Unauthenticated
        '403':
          description: forbidden
        '404':
          description: session or user id not found
        '500':
          description: internal server error
components:
  schemas:
    Questions:
      type: object
      required:
      - question_id
      - options
      properties:
        question_id:
          type: string
          example: ques1
        question:
          type: string
          example: What is Go?
        options:
          type: array
          items:
            type: string
          example:
            - Language
            - Animal
            - Game
            
  requestBodies:
    GenerateQuiz:
      description: Data to generate a quiz
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              topic:
                type: string
              user_id:
                type: string
              session_id:
                type: string
            example:
              topic: go
              user_id: user1
              session_id: ssid1

    StoreAnswer:
      description: Data of answer to questions
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                session_id:
                  type: string
                  example: ssid1
                answers:
                  type: array
                  items:
                    type: object
                    properties:
                      ques_id:
                        type: string
                        example: ques1
                      answer:
                        type: string
                        example: a
                  
              

